/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemilihan.dokter;

/**
 *
 * @author diniristanti
 */
public class pilihdokter extends javax.swing.JFrame {

    /**
     * Creates new form pilihdokter
     */
    public pilihdokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pilih1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        goldar = new javax.swing.JTextField();
        waktu = new javax.swing.JTextField();
        wni = new javax.swing.JTextField();
        spesialis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 110, 20);

        jLabel2.setText("Pilih Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 60, 14);

        pilih1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "dr. Farras Yassar", "dr. Anisa Putri", "dr. Harun Fajar" }));
        pilih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih1ActionPerformed(evt);
            }
        });
        getContentPane().add(pilih1);
        pilih1.setBounds(110, 40, 190, 30);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("IDENTITAS"));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setText("Nama");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(11, 12, 27, 14);

        jLabel5.setText("Alamat");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 40, 33, 14);

        jLabel6.setText("Usia");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 70, 20, 14);

        jLabel7.setText("Jenis Kelamin");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 100, 70, 14);

        jLabel8.setText("Golongan Darah");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 130, 80, 14);

        jLabel9.setText("Status");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 160, 31, 14);

        jLabel10.setText("Kewarganegaraan");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 190, 90, 14);

        jLabel11.setText("Waktu Praktek");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 220, 70, 14);

        jLabel12.setText("Dokter Spesialis");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 250, 75, 14);

        alamat.setEditable(false);
        jPanel2.add(alamat);
        alamat.setBounds(110, 40, 180, 20);

        nama.setEditable(false);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel2.add(nama);
        nama.setBounds(110, 10, 180, 20);

        jenis.setEditable(false);
        jPanel2.add(jenis);
        jenis.setBounds(110, 100, 180, 20);

        usia.setEditable(false);
        jPanel2.add(usia);
        usia.setBounds(110, 70, 180, 20);

        status.setEditable(false);
        jPanel2.add(status);
        status.setBounds(110, 160, 180, 20);

        goldar.setEditable(false);
        jPanel2.add(goldar);
        goldar.setBounds(110, 130, 180, 20);

        waktu.setEditable(false);
        jPanel2.add(waktu);
        waktu.setBounds(110, 220, 180, 20);

        wni.setEditable(false);
        jPanel2.add(wni);
        wni.setBounds(110, 190, 180, 20);

        spesialis.setEditable(false);
        jPanel2.add(spesialis);
        spesialis.setBounds(110, 250, 180, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 310, 290);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 90, 330, 370);

        setBounds(0, 0, 416, 489);
    }// </editor-fold>//GEN-END:initComponents

    private void pilih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih1ActionPerformed
        // TODO add your handling code here:
        if(pilih1.getSelectedItem().equals("dr. Farras Yassar")){
            nama.setText("DR. Farras Yassar ");
            alamat.setText("Jl. Surabaya 16, Malang");
            usia.setText("20 Tahun");
            jenis.setText("Laki-Laki");
            goldar.setText("A");
            status.setText("Belum Menikah ");
            wni.setText("Indonesia");
            spesialis.setText("Dokter Umum");
            waktu.setText(" Pagi (07.00-15.00)");
        }
        else
        if(pilih1.getSelectedItem().equals("dr. Anisa Putri")){
            nama.setText("DR. Anisa Putri");
            alamat.setText("Jl. Veteran 3, Malang");
            usia.setText("20 Tahun");
            jenis.setText("Perempuan");
            goldar.setText("O");
            status.setText("Belum Menikah");
            wni.setText("Indonesia");
            spesialis.setText("Dokter Gigi");
            waktu.setText(" Sore (16.00-22.00)");
        }
        else
        if(pilih1.getSelectedItem().equals("dr. Harun Fajar")){
            nama.setText("DR. Harun Fajar ");
            alamat.setText("Jl. Bandung 9, Malang");
            usia.setText("20 Tahun");
            jenis.setText("Laki-Laki");
            goldar.setText("B");
            status.setText("Belum Menikah");
            wni.setText("Indonesia");
            spesialis.setText("Dokter Gizi");
            waktu.setText(" Malam (22.00-06.00)");
        }
        

    }//GEN-LAST:event_pilih1ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihdokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField goldar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> pilih1;
    private javax.swing.JTextField spesialis;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    private javax.swing.JTextField waktu;
    private javax.swing.JTextField wni;
    // End of variables declaration//GEN-END:variables
}
